// Finding 17: the database meter in System > Health, and Reclaim space.
const { chromium } = require('playwright-core');
const BASE = 'http://localhost:5001';
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const res = []; const check = (n, ok, d = '') => { res.push(ok); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}  ${d}`); };
const errs = [];
(async () => {
  const login = await fetch(BASE + '/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'coffeecue', password: 'adminpassword' }) }).then(r => r.json());
  const TOKEN = login.token || login.access_token;
  const H = { 'Content-Type': 'application/json', Authorization: 'Bearer ' + TOKEN };
  const full = await fetch(BASE + '/api/health/full', { headers: H }).then(r => r.json());
  const st = (full.checks || {}).storage || {};
  check('/health/full carries a storage check with measured sizes', st.db_bytes > 0 && st.volume_bytes > 0 && typeof st.used_pct === 'number', st.detail);
  check('it names the largest table and the largest setting', (st.tables || [])[0]?.name === 'settings' && (st.settings_keys || [])[0]?.key === 'display_bg_video', `${st.tables?.[0]?.name}, ${st.settings_keys?.[0]?.key}`);
  const before = st.settings_reclaimable_bytes || 0;
  check('the copy has reclaimable space to test with', before > 5 * 1048576, `${Math.round(before / 1048576)} MB reclaimable`);
  const anon = await fetch(BASE + '/api/health/storage/reclaim', { method: 'POST' }).then(r => r.status);
  check('reclaim refuses without a login', anon === 401, `HTTP ${anon}`);

  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const c = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  await c.addInitScript((t) => { localStorage.setItem('coffee_system_token', t); localStorage.setItem('coffee_system_user', JSON.stringify({ username: 'coffeecue', role: 'admin', id: 1 })); }, TOKEN);
  const p = await c.newPage(); p.on('pageerror', e => errs.push(e.message.slice(0, 140)));
  await p.goto(BASE + '/run#system/health', { waitUntil: 'load' }); await sleep(6000);
  const t0 = await p.evaluate(() => document.body.innerText);
  check('System > Health shows the Database storage tile', /Database storage/.test(t0) && /Reclaimable:/.test(t0));
  check('and the Database volume meter with real MB', /Database volume/.test(t0) && /\d+ MB \/ \d+ MB/.test(t0), (t0.match(/Database volume[^\n]*\n[^\n]*/) || [''])[0].replace(/\n/g, ' '));
  check('says where Railway\'s higher number comes from', /Railway's gauge reads a little higher/.test(t0));
  await p.screenshot({ path: 'storage_tile.png', fullPage: true });
  const btn = p.getByRole('button', { name: /^Reclaim \d+ MB$/ }).first();
  check('a Reclaim button is offered when it is worth it', await btn.count() > 0);
  await btn.click(); await sleep(800);
  const t1 = await p.evaluate(() => document.body.innerText);
  check('the dialog says quiet moment and shows table vs live size', /Do this at a quiet moment/.test(t1) && /live data/.test(t1));
  await p.screenshot({ path: 'storage_dialog.png' });
  await p.getByRole('dialog').getByRole('button', { name: /^Reclaim \d+ MB$/ }).click(); await sleep(7000);
  const t2 = await p.evaluate(() => document.body.innerText);
  check('the tile reports what came back', /given back/.test(t2), (t2.match(/[^\n]*given back[^\n]*/) || [''])[0]);
  const after = await fetch(BASE + '/api/health/full', { headers: H }).then(r => r.json());
  const st2 = (after.checks || {}).storage || {};
  check('reclaimable is now ~0 and the table shrank', (st2.settings_reclaimable_bytes || 0) < 2 * 1048576 && st2.settings_bytes < st.settings_bytes, `${Math.round(st.settings_bytes / 1048576)} MB -> ${Math.round(st2.settings_bytes / 1048576)} MB`);
  const btn2 = p.getByRole('button', { name: /^Reclaim \d+ MB$/ });
  check('the button goes away when there is nothing to reclaim', await btn2.count() === 0);
  await p.screenshot({ path: 'storage_after.png', fullPage: true });
  await browser.close();
  check('no page errors', errs.length === 0, errs.join(' || ').slice(0, 200));
  console.log(`\n${res.filter(Boolean).length}/${res.length} passed`);
  process.exit(res.every(Boolean) ? 0 : 1);
})().catch(e => { console.error('HARNESS ERROR', e); process.exit(2); });
