[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PATH = "/opt/venv/bin:$PATH"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt",
  "ls -la /opt/venv/bin/",
  "/opt/venv/bin/pip list"
]

[start]
cmd = "/opt/venv/bin/python run_server.py"