// Snapshot the running copy's /design sheet into standalone HTML:
//   design-system/cupq_design_sheet.html   -- the whole sheet (share / artifact)
//   design-system/{foundations,components}/*.html -- one card per section,
//       each starting with <!-- @dsCard group="..." --> for Claude Design.
// The React components in src/design are the source of truth; this only
// captures what they render. Run with the copy up (./next.sh):
//   node testbench/design/snapshot.js [http://localhost:5001]
// Needs playwright-core + Chrome (npm i playwright-core in this folder).
const { chromium } = require('playwright-core');
const fs = require('fs'); const path = require('path');
const BASE = process.argv[2] || 'http://localhost:5001';
const OUT = path.join(__dirname, '..', '..', 'design-system');
const GROUP = { 'Colour': 'Foundations', 'Type': 'Foundations', 'Space and shape': 'Foundations', 'Area marks': 'Marks', 'Buttons': 'Actions', 'Status pills': 'Status', 'Station chips': 'Status', 'The order card': 'Cards', 'The board number': 'Cards', 'Tab bar': 'Navigation', 'Sidebar': 'Navigation', 'PIN panel': 'Panels' };
(async () => {
  for (const d of ['foundations', 'components']) fs.mkdirSync(path.join(OUT, d), { recursive: true });
  const b = await chromium.launch({ channel: 'chrome', headless: true });
  const p = await (await b.newContext({ viewport: { width: 1024, height: 768 } })).newPage();
  await p.goto(BASE + '/design', { waitUntil: 'load' }); await new Promise(r => setTimeout(r, 3500)); await p.evaluate(() => document.fonts.ready);
  const cssHref = await p.evaluate(() => [...document.querySelectorAll('link[rel=stylesheet]')].map(l => l.href).find(h => /static\/css\/main/.test(h)));
  const css = await (await fetch(cssHref)).text();
  const head = (title) => `<title>${title}</title>\n<link rel="preconnect" href="https://fonts.googleapis.com">\n<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap">\n<style>\n${css}\nbody{margin:0;background:#F6F1EA}\n</style>\n`;
  const sheet = await p.evaluate(() => document.querySelector('.cq').outerHTML);
  fs.writeFileSync(path.join(OUT, 'cupq_design_sheet.html'), head('CupQ Design System') + '<!-- Static snapshot of the copy\'s /design page. -->\n' + sheet + '\n');
  const sections = await p.evaluate(() => [...document.querySelectorAll('.cq section')].map(s => ({ title: s.querySelector('h2').textContent.trim(), html: s.outerHTML })));
  const made = [];
  for (const s of sections) {
    const group = GROUP[s.title] || 'Components';
    const slug = s.title.toLowerCase().replace(/^the /, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const file = `${group === 'Foundations' ? 'foundations' : 'components'}/${slug}.html`;
    fs.writeFileSync(path.join(OUT, file), `<!-- @dsCard group="${group}" -->\n` + head('CupQ · ' + s.title) + `<div class="cq" style="padding:24px">\n${s.html}\n</div>\n`);
    made.push(file);
  }
  fs.writeFileSync(path.join(OUT, 'README.md'), `# CupQ design system\n\nGenerated by testbench/design/snapshot.js from the running copy (/design). Source of truth: src/design/tokens.css and src/design/*.js.\n\nTo push to Claude Design: run /design-login once in an interactive Claude Code session, then ask Claude to sync this folder.\n\n${made.map(f => '- ' + f).join('\n')}\n`);
  console.log(`wrote ${made.length + 1} files to ${OUT}`); await b.close();
})();
